### ISSUE TITLE
[SDL2] overwriting of window borders in some conditions on amigaos4

### ISSUE THREAD

**Issue by kas1e** [AmigaPorts/SDL_old#146]
As we discuss on amigans there is the same kind of issue as we had with shaderjoy when resizing a window from bigger to smaller size. Quote from Capehill:

Reproducible with some examples: testoverlay2, teststreaming. Not producible with testdrawchessboard.

Originally issue was found with some sdl2 port, which initialization code looks like this:

```
window_ = SDL_CreateWindow(WINDOW_TITLE,
                           SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
                           pop_window_width, pop_window_height, flags);
// Make absolutely sure that VSync will be off, to prevent timer issues.
SDL_SetHint(SDL_HINT_RENDER_VSYNC, "0");
renderer_ = SDL_CreateRenderer(window_, -1 , SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
SDL_RendererInfo renderer_info;
if (SDL_GetRendererInfo(renderer_, &renderer_info) == 0) {
    if (renderer_info.flags & SDL_RENDERER_TARGETTEXTURE) {
        is_renderer_targettexture_supported = true;
    }
}
```

Which means issues probably happens in compositing renderer path.

**Comment by capehill** [comment]
testdrawchessboard uses SW rendering, so blitting happens via SDL_os4framebuffer.c and there are  differences when compared to blitting in SDL_render_compositing.c. 

1) SDL_Window vs. Window width & height. Maybe there are not in sync
2) Framebuffer code uses min() to limit blitting area

Should be also tested with MiniGL renderer. Ogles2 is not affected because ogles2 handles the blitting internally.

**Comment by capehill** [comment]
Should be fixed but if not, please re-open.
