### ISSUE TITLE
White line at the bottom

### ISSUE THREAD

**Issue by afalkenhahn** [AmigaPorts/SDL_old#150]
Here's another issue. This program draws everything to a 360x284 texture and then draws this texture scaled to the current screen dimensions. This works fine except that the bottom line is white although it should be black. It's a minor issue, though.

Here is a test program:
[temp.zip](https://github.com/AmigaPorts/SDL/files/4798920/temp.zip)

**Comment by capehill** [comment]
Also on the right side with resolution 1920*1200. Issue seems to depend on the used screen mode. I don't know how driver is using the fixed point scaling factor, but if there is no rounding, it might have some problem.

I tested this by disabling the DEST_Width/Height parameters (making them default) and issue is not caused by clipping. On the other, by increasing ScaleX/Y, white edges disappeared.

I suppose using vertex mode of CompositeTags might be a solution.

**Comment by afalkenhahn** [comment]
But of course it's just a minor nuisance. The other issue I reported concerning alpha transparency is a much bigger problem and should be given top priority :)

**Comment by afalkenhahn** [comment]
I should add that sometimes there's also a white line at the right, not only at the bottom. For example if you run the Turrican 2 example script that comes with RebelSDL in full screen mode. There are white lines at the bottom and the right.

**Comment by capehill** [comment]
Yes, it depends on scalex/scaley values (and thus srcrect vs dstrect dimensions) as far as I undertand. It seems like a bug in graphics.library.

**Comment by afalkenhahn** [comment]
Ok this makes a fix rather unlikely...

**Comment by capehill** [comment]
Turns out the issue has been reported already to OS4 team a long time ago.

I think I change it to use vertex/triangle mode in 2.0.14.

**Comment by capehill** [comment]
Closing with 2.0.14 RC1.
